### ISSUE TITLE
'More Cupcakes' button appears twice

### ISSUE THREAD

**Issue by sinc0115** [sinc0115/Rubys-Cupcakes#101]
On the homepage, in the "Crowd Pleasing Treats" section, the "More Cupcakes" button appears twice. Please remove one of them.

**Comment by Sukhija-Aniket** [comment]
removed duplicate buttons, images and paragraphs.

**Comment by npkeerthi** [comment]
"More Cupcakes" button appears twice.
Updated By removing the right one ✔
@sinc0115  Have a review on it
