### ISSUE TITLE
Tidy up "New Fall Flavour" section

### ISSUE THREAD

**Issue by sinc0115** [sinc0115/Rubys-Cupcakes#102]
On the homepage, the "New Fall Flavour" section is looking a little messy. Please tidy up the styling a little and make sure it's responsive (both for mobile screens and really big screens). 
Reference the prototype in the README.md for more guidance on how it should look.

**Comment by alyssamelody** [comment]
Hello @sinc0115 ! I would like to try fixing this issue.
