### ISSUE TITLE
Change content font

### ISSUE THREAD

**Issue by sinc0115** [sinc0115/Rubys-Cupcakes#22]
The font-family of the content should be Roboto (see README.md for google fonts link).

**Comment by wali39** [comment]
close this issue font-family already added in css file

**Comment by sinc0115** [comment]
Font has been added to the page in a few places, but I spot a number of <p> elements that have not had the font changed, yet.

**Comment by Kakuli-coder** [comment]
Hey @sinc0115 ! I can fix this issue. Kindly assign this to me.

**Comment by agraghav26** [comment]
Hey @sinc0115 !
Can I work on this issue ?
Please assign it to me

**Comment by agraghav26** [comment]
Hey @sinc0115 !
I have made my PR  #71  for this issue .Please review it and accept it.
