### ISSUE TITLE
Add descriptive alt text

### ISSUE THREAD

**Issue by sinc0115** [sinc0115/Rubys-Cupcakes#42]
Add descriptive alt text to the cupcake images. Good alt text describes the purpose of the image (not just what the picture is). Our users want to know what the cupcakes are made of and what they will taste like. Please describe each cupcake as briefly as you can. (i.e. alt="Chocolate cake with maple frosting, bacon bits, caramel drizzle").

Here's some further reading about alt text: 
https://www.w3.org/WAI/tutorials/images/tips/
https://www.a11yproject.com/posts/2013-01-14-alt-text/ 
https://www.deque.com/blog/great-alt-text-introduction/

**Comment by Ray0Emma** [comment]
I'd love to do that

**Comment by sinc0115** [comment]
Thanks @Ray0Emma , go for it!
