### ISSUE TITLE
Give the About page some breathing room

### ISSUE THREAD

**Issue by sinc0115** [sinc0115/Rubys-Cupcakes#68]
The About page is looking a little bit squished. Please give it a little extra breathing room between sections. 
You can look at the prototype for guidance, or add spacing as you see fit. Just make sure it matches the overall styling of the site.

**Comment by sulledy221** [comment]
I would like to try and tackle this!

**Comment by sinc0115** [comment]
Thanks @sulledy221 , go for it!
