### ISSUE TITLE
Add links to contact information

### ISSUE THREAD

**Issue by sinc0115** [sinc0115/Rubys-Cupcakes#94]
On the Contact page, there is an email and phone number for contacting Ruby. Please make this links with the appropriate attributes for their types. 
![image](https://user-images.githubusercontent.com/46421126/139354081-096e1d45-8392-4405-99ec-60bf0e7ac9d2.png)

**Comment by fallowamber** [comment]
Hey @sinc0115, could I work on it? I see that the contact information haven't been linked.
